apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-mongodb-app
  template:
    metadata:
      labels:
        app: flask-mongodb-app
    spec:
      containers:
      - name: flask-app
        image: your-docker-registry/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/mydatabase"
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: flask-mongodb-service
spec:
  selector:
    app: flask-mongodb-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: flask-mongodb-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None